security:
  encoders:
    App\Entity\AdhesionBibliotheque:
      algorithm: bcrypt
    App\Entity\SuperAdmin:
      algorithm: bcrypt
  providers:
    users_in_memory: { memory: null }
    superadmin:
      entity: { class: App\Entity\SuperAdmin, property: email }
        # class: 'App\entity\SuperAdmin'
        # property: 'email'
    user:
      entity: { class: App\Entity\AdhesionBibliotheque, property: email }
        # class: 'App\entity\AdhesionBibliotheque'
        # property: 'email'
    all_users:
      chain:
        providers: ['superadmin', 'user']
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      lazy: true
      provider: all_users
      guard:
        authenticators:
          - App\Security\AppAdminAuthenticator
      logout:
        path: app_logout
        # where to redirect after logout
        target: app_login
  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#firewalls-authentication

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
     - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
     - { path: ^/biblio, roles: ROLE_USER }
